# Glassdoor Jobs Data Cleaning

## Objective
Clean and transform raw Glassdoor job posting data to prepare it for analysis.

## Dataset
- Source: Glassdoor job postings dataset
- Contains job titles, salary estimates, company info, and descriptions

## Tools Used
- Python
- Pandas

In [ ]:
## 1. Load Dataset
import pandas as pd
df = pd.read_csv('glassdoor_jobs.csv')

## 2. Initial Data Inspection
- Shape of dataset
- Column overview
- Missing values

In [ ]:
df.head()

#Cleaning tasks
#salary parsing
#company name
#state field
#age of company
#parsing of job description (python, etc)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [ ]:
df = df[df['Salary Estimate'] != '-1']
pd.set_option('display.max_rows', None)
df.shape
pd.set_option('display.max_rows', None)

## 3. Salary Cleaning
- Remove invalid salary rows
- Extract min, max, and average salary
- Identify hourly vs yearly salaries
- Employer provided salary flag

In [ ]:
#Standardizing Salary column by removing texts and dollar signs/ salary parsing
salary = df['Salary Estimate'].apply(lambda x: x.split('(')[0])
df.shape

salary
minus_kd = salary.apply(lambda x: x.replace('K', '').replace('$', ''))
minus_kd.head()

0                                       53-91
1                                      63-112
2                                       80-90
3                                       56-97
4                                      86-143
5                                      71-119
6                                       54-93
7                                      86-142
8                                       38-84
9                                     120-160
10                                    126-201
11                                     64-106
12                                    106-172
13                                      46-85
14                                     83-144
15                                    102-190
16                                     67-137
17                                    118-189
18                                    110-175
19                                     64-111
20                                     81-130
21                                     73-119
22                                     86-139
23                                     63-105
25                                    109-177
26                                     63-110
27                                     75-124
28                                      34-61
29                                     63-105
30                                      80-90
31                                      56-97
32                                     72-120
33                                     86-143
34                                     93-149
35                                     85-140
36                                     77-135
37                                     82-132
38                                     83-137
39                                    115-180
40                                     74-138
41                                     64-112
43                                     68-129
44                                    110-175
45                                     52-113
46                                     110-150
48            Employer Provided Salary:150-160
49                                    158-211
50                                      20-39
51                                     56-117
52                                      63-99
54                                     68-114
55                                     86-143
56                                      41-95
57                                     86-144
58                                     80-139
59                                      56-95
60                                    120-189
61                                    111-176
62                                      54-93
63                                     71-119
65                                     82-132
66                                     84-146
67                                    107-172
68                                      49-85
70                                     61-109
72                                     88-148
73                                      60-99
75                                      41-72
76                                     96-161
77                                     65-130
78                                      52-81
79                                    139-220
80                                     50-102
81                                     85-139
82                                     74-122
83                                     99-157
84                                     79-222
85                                     57-118
86                                     83-137
87                                     86-141
88                                     94-154
89                                      37-76
90                                    100-160
91                                     55-100
92                                     60-114
93                                      39-68
94                                    106-172
95                                     86-142
96                                     64-107
97                                      31-65
99                                      34-62
101                                   117-231
102                                    64-106
104                                    79-134
105                                     52-93
106                                    55-116
107                                    72-123
108                                    74-124
109                                     40-73
110                                   102-164
112                                    89-153
113                                    61-110
116                                    65-110
117                                    200-275
118                                    68-123
119                                    80-129
120                                     41-72
122                                     39-71
123                                     38-85
124                                   121-193
125                                    54-102
126                                    83-144
127                                   120-160
128                                   102-163
129                                    76-140
130                                    60-101
131                                    82-133
132                                    65-125
136                                    91-148
137                                    95-173
138                                    77-124
139                                    80-135
140                                    85-159
141                                     80-105
142                                     43-81
143                                     29-50
145                                    82-133
146                                     26-55
147                                    61-118
148                                    60-102
150                                   112-182
152                                    64-106
153                                    51-112
154                                   113-223
156                                    72-129
157                                    71-123
158                                    64-106
159                                   118-189
161           Employer Provided Salary:120-145
162                                    80-120
164                                    80-130
166                                    59-115
167                                    71-136
168                                    81-167
169                                     49-85
170                                    60-114
171                                    71-204
172                                    75-125
174                                    77-136
175                                    74-123
177                                     44-78
178                                    65-148
179                                    59-110
180                                    85-134
181                                   124-204
182                                   131-207
183                                   110-174
185                                    52-101
187                                    81-133
188                                   132-211
190                                    73-119
191                                   110-175
192                                    74-140
193                                   100-190
194                                     43-80
197                             17-24 Per Hour
198                                    91-149
199                                     42-82
200                                   116-185
201                                    59-116
202                                     48-95
203                                     31-72
204                                   105-198
205                                    55-100
206                                    98-182
207                                    73-124
208           Employer Provided Salary:200-250
209                             21-34 Per Hour
210                                   117-206
211                                   111-183
212                                     44-78
213                                    81-159
215                                    83-166
216                                   114-182
217                                     42-76
221                                   114-179
223                                    60-123
224                                   100-166
225                                   108-173
226                                     48-93
228                                    54-115
229                                    60-127
230                                    90-179
233                                   138-224
234                                    54-115
235                                    190-220
239                                     35-62
240                             18-25 Per Hour
242                                     39-66
243                                    81-167
245                                     42-86
246                                    69-127
247                             21-34 Per Hour
248                                     40-68
250                                    49-113
251                                    75-140
253                                    86-139
254                                    66-112
255                                    76-125
256                                     44-86
257                             15-25 Per Hour
258                                     53-92
259                                     44-78
260                                    85-134
262                                    59-110
263                                    64-111
264                                    65-120
265                                    60-103
266                                    53-105
267                                   124-204
268                                   131-207
269                                   110-174
270                                     33-62
273                                    52-101
274                                     48-90
275                                     34-64
276                                   132-211
277                                    81-133
278                                     42-76
281                                    66-111
282                                    74-140
284                                    63-110
285                                    63-105
288                                    91-138
289                                   100-190
290                                    62-114
291                                    71-129
292                                     43-80
293                                    74-119
295                                     55-97
296                                      15-16
299                                    61-106
300                                    91-149
302                                   127-199
305                                    74-126
306                                     33-72
307                             17-24 Per Hour
308                                     37-63
309                                    67-119
310                                    72-117
311                                   116-185
312                                    78-126
313                                     42-82
314                                    59-116
316                                    63-105
317                                   109-177
318                                   116-194
319                                     48-95
320                                    83-133
322                                   105-198
323                                     31-72
324                                    98-182
325                                    55-100
326                                     45-82
328                                    83-135
330                                    70-122
331           Employer Provided Salary:200-250
332                                    70-132
333                                    73-124
334                                    54-101
335                                   117-206
337                             21-34 Per Hour
339                                   111-183
341                                    68-112
342                                     42-74
344                                     44-78
346                                    81-159
347                                    95-161
348                                    75-124
349                                    72-120
350                                    76-126
351                                   114-182
352                                   108-176
353                                   130-208
354                                    83-166
355                                     42-76
356                                     37-68
357                                     52-99
358                                   105-173
362                                    71-134
364                                     39-82
366                                   114-179
367                                    88-162
368                                    60-102
369                                   100-166
370                                     55-99
371                                    67-117
372                                    92-150
375                                   116-209
376                                     38-82
377             Employer Provided Salary:85-90
379                                    62-119
380                                    86-143
381                                    93-149
382                                    84-136
383                                    60-123
384                                     52-89
386                                     48-93
387                                     56-97
388                                    65-119
390                                   108-173
391                                    63-101
392                                    54-115
394                                    90-179
396                                   127-202
397                                     31-57
398                                    60-127
399                                    75-143
400                                   105-194
401                                     45-86
403                                    95-154
406                                    80-148
407                                     36-62
409                                    54-115
410                                     50-92
411                                    67-135
412                                    82-132
413                                    85-140
414                                   138-224
415                                     42-80
416                                    190-220
417                                    68-139
419                                     34-92
420                                     54-71
421                                    65-124
425                                     35-62
426                                   109-200
427                             18-25 Per Hour
428                                    61-113
429                                     39-66
430                                     43-86
431                                    74-149
433                                   113-196
434                                    81-167
435                                    97-160
437                             24-39 Per Hour
442                                     42-86
443                                    69-127
444                                   110-175
446                                   102-172
447                                    74-124
448                                     40-68
449                                   108-171
450                                    76-142
452                                   202-306
454                                     49-97
455                                    49-113
456                             21-34 Per Hour
458                                    65-134
459                                     32-59
461                                    87-158
462                                   107-173
463                                     56-99
464    Employer Provided Salary:25-28 Per Hour
466                                    80-155
467                                     43-98
468                                     45-78
469                                     44-96
470                                    50-110
471                                    61-119
472           Employer Provided Salary:100-140
473                                     56-91
476                                    68-114
477           Employer Provided Salary:150-160
479                                   101-158
482                                   125-210
483                                     43-77
485                                   139-221
486                                     44-86
487                                    78-147
488                                    65-110
489                                     37-66
490                                     38-64
491                                     43-82
492                                     90-110
493                                    61-109
494                                    93-151
495                                     52-81
496                                    40-101
497                                    97-180
498                                    81-134
499                                    84-157
500                                    49-113
501                                    68-139
502                                    75-140
505                                   121-203
506                                     52-85
507                                    81-140
508                                     63-99
509                                    110-150
510                                    83-148
512                                    60-101
516                                     31-55
517                                   102-178
518           Employer Provided Salary:110-130
519                                     48-85
520                                    66-123
521                                    92-146
522                             21-29 Per Hour
523                             10-17 Per Hour
524                                   150-239
525                                     52-91
526                                     82-129
528                                    47-101
530                                     49-76
532                                     43-88
533                                   124-199
534                                     52-93
535                                    97-181
537                                   100-173
538                                     53-96
539                                     65-96
540                                     56-95
541                                   111-176
542                                    75-127
543                                    65-119
544                                     56-97
545                                   108-173
546                                    94-139
548                                   176-289
549                                    92-149
550                                    63-101
552                                    54-115
554                                   118-188

In [ ]:
#We still see that there are rows with hourly pay & employer provided salary hence creating columns for the same
df['hourly'] = df['Salary Estimate'].apply(lambda x: 1 if 'per hour' in x.lower() else 0)
df['employer_provided'] = df['Salary Estimate'].apply(lambda x: 1 if 'employer provided salary' in x.lower() else 0)
df[df['hourly'] == 1].head(10)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer_provided
197,197,Medical Lab Scientist,$17-$24 Per Hour(Glassdoor est.),Overview\n\nAbout\n\n\nTower Health is a stron...,3.6,Tower Health\n3.6,"West Reading, PA","Reading, PA",5001 to 10000 employees,2017,Nonprofit Organization,Health Care Services & Hospitals,Health Care,Unknown / Non-Applicable,-1,1,0
209,209,MED TECH/LAB SCIENTIST - LABORATORY,$21-$34 Per Hour(Glassdoor est.),Evening: 3P-1130P or Night Shift 11P-730A\n\nI...,3.6,Beebe Healthcare\n3.6,"Lewes, DE","Lewes, DE",1001 to 5000 employees,1935,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),-1,1,0
240,240,Medical Laboratory Scientist,$18-$25 Per Hour(Glassdoor est.),Description\nMedical Laboratory Scientist - Te...,4.0,Texas Health Huguley Hospital\n4.0,"Burleson, TX","Arlington, TX",1001 to 5000 employees,1977,Hospital,Health Care Services & Hospitals,Health Care,$50 to $100 million (USD),-1,1,0
247,247,MED TECH/LAB SCIENTIST- SOUTH COASTAL LAB,$21-$34 Per Hour(Glassdoor est.),Day Shift: 7A-330P. Holidays and every other w...,3.6,Beebe Healthcare\n3.6,"Millville, DE","Lewes, DE",1001 to 5000 employees,1935,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),-1,1,0
257,257,Medical Technologist / Clinical Laboratory Sci...,$15-$25 Per Hour(Glassdoor est.),The incumbent performs a broad range of labora...,3.4,"Veterans Affairs, Veterans Health Administrati...","New Orleans, LA","Washington, DC",10000+ employees,1930,Government,Federal Agencies,Government,Unknown / Non-Applicable,-1,1,0
307,307,Medical Lab Scientist,$17-$24 Per Hour(Glassdoor est.),Overview\n\nAbout\n\n\nTower Health is a stron...,3.6,Tower Health\n3.6,"West Reading, PA","Reading, PA",5001 to 10000 employees,2017,Nonprofit Organization,Health Care Services & Hospitals,Health Care,Unknown / Non-Applicable,-1,1,0
337,337,MED TECH/LAB SCIENTIST - LABORATORY,$21-$34 Per Hour(Glassdoor est.),Evening: 3P-1130P or Night Shift 11P-730A\n\nI...,3.6,Beebe Healthcare\n3.6,"Lewes, DE","Lewes, DE",1001 to 5000 employees,1935,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),-1,1,0
427,427,Medical Laboratory Scientist,$18-$25 Per Hour(Glassdoor est.),Description\nMedical Laboratory Scientist - Te...,4.0,Texas Health Huguley Hospital\n4.0,"Burleson, TX","Arlington, TX",1001 to 5000 employees,1977,Hospital,Health Care Services & Hospitals,Health Care,$50 to $100 million (USD),-1,1,0
437,437,Clinical Laboratory Scientist,$24-$39 Per Hour(Glassdoor est.),POSITION PURPOSE:\nPerforms CLIA moderate and ...,3.7,Vail Health\n3.7,"Vail, CO","Vail, CO",501 to 1000 employees,1966,Hospital,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),-1,1,0
456,456,MED TECH/LAB SCIENTIST- SOUTH COASTAL LAB,$21-$34 Per Hour(Glassdoor est.),Day Shift: 7A-330P. Holidays and every other w...,3.6,Beebe Healthcare\n3.6,"Millville, DE","Lewes, DE",1001 to 5000 employees,1935,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$100 to $500 million (USD),-1,1,0

In [ ]:
#creating a salary column with no texts
min_hr = minus_kd.apply(lambda x: x.lower().replace('per hour', '').replace('employer provided salary:', ''))
min_hr.head()

0        53-91
1       63-112
2        80-90
3        56-97
4       86-143
5       71-119
6        54-93
7       86-142
8        38-84
9      120-160
10     126-201
11      64-106
12     106-172
13       46-85
14      83-144
15     102-190
16      67-137
17     118-189
18     110-175
19      64-111
20      81-130
21      73-119
22      86-139
23      63-105
25     109-177
26      63-110
27      75-124
28       34-61
29      63-105
30       80-90
31       56-97
32      72-120
33      86-143
34      93-149
35      85-140
36      77-135
37      82-132
38      83-137
39     115-180
40      74-138
41      64-112
43      68-129
44     110-175
45      52-113
46      110-150
48      150-160
49     158-211
50       20-39
51      56-117
52       63-99
54      68-114
55      86-143
56       41-95
57      86-144
58      80-139
59       56-95
60     120-189
61     111-176
62       54-93
63      71-119
65      82-132
66      84-146
67     107-172
68       49-85
70      61-109
72      88-148
73       60-99
75       41-72
76      96-161
77      65-130
78       52-81
79     139-220
80      50-102
81      85-139
82      74-122
83      99-157
84      79-222
85      57-118
86      83-137
87      86-141
88      94-154
89       37-76
90     100-160
91      55-100
92      60-114
93       39-68
94     106-172
95      86-142
96      64-107
97       31-65
99       34-62
101    117-231
102     64-106
104     79-134
105      52-93
106     55-116
107     72-123
108     74-124
109      40-73
110    102-164
112     89-153
113     61-110
116     65-110
117     200-275
118     68-123
119     80-129
120      41-72
122      39-71
123      38-85
124    121-193
125     54-102
126     83-144
127    120-160
128    102-163
129     76-140
130     60-101
131     82-133
132     65-125
136     91-148
137     95-173
138     77-124
139     80-135
140     85-159
141      80-105
142      43-81
143      29-50
145     82-133
146      26-55
147     61-118
148     60-102
150    112-182
152     64-106
153     51-112
154    113-223
156     72-129
157     71-123
158     64-106
159    118-189
161     120-145
162     80-120
164     80-130
166     59-115
167     71-136
168     81-167
169      49-85
170     60-114
171     71-204
172     75-125
174     77-136
175     74-123
177      44-78
178     65-148
179     59-110
180     85-134
181    124-204
182    131-207
183    110-174
185     52-101
187     81-133
188    132-211
190     73-119
191    110-175
192     74-140
193    100-190
194      43-80
197      17-24
198     91-149
199      42-82
200    116-185
201     59-116
202      48-95
203      31-72
204    105-198
205     55-100
206     98-182
207     73-124
208     200-250
209      21-34
210    117-206
211    111-183
212      44-78
213     81-159
215     83-166
216    114-182
217      42-76
221    114-179
223     60-123
224    100-166
225    108-173
226      48-93
228     54-115
229     60-127
230     90-179
233    138-224
234     54-115
235     190-220
239      35-62
240      18-25
242      39-66
243     81-167
245      42-86
246     69-127
247      21-34
248      40-68
250     49-113
251     75-140
253     86-139
254     66-112
255     76-125
256      44-86
257      15-25
258      53-92
259      44-78
260     85-134
262     59-110
263     64-111
264     65-120
265     60-103
266     53-105
267    124-204
268    131-207
269    110-174
270      33-62
273     52-101
274      48-90
275      34-64
276    132-211
277     81-133
278      42-76
281     66-111
282     74-140
284     63-110
285     63-105
288     91-138
289    100-190
290     62-114
291     71-129
292      43-80
293     74-119
295      55-97
296       15-16
299     61-106
300     91-149
302    127-199
305     74-126
306      33-72
307      17-24
308      37-63
309     67-119
310     72-117
311    116-185
312     78-126
313      42-82
314     59-116
316     63-105
317    109-177
318    116-194
319      48-95
320     83-133
322    105-198
323      31-72
324     98-182
325     55-100
326      45-82
328     83-135
330     70-122
331     200-250
332     70-132
333     73-124
334     54-101
335    117-206
337      21-34
339    111-183
341     68-112
342      42-74
344      44-78
346     81-159
347     95-161
348     75-124
349     72-120
350     76-126
351    114-182
352    108-176
353    130-208
354     83-166
355      42-76
356      37-68
357      52-99
358    105-173
362     71-134
364      39-82
366    114-179
367     88-162
368     60-102
369    100-166
370      55-99
371     67-117
372     92-150
375    116-209
376      38-82
377       85-90
379     62-119
380     86-143
381     93-149
382     84-136
383     60-123
384      52-89
386      48-93
387      56-97
388     65-119
390    108-173
391     63-101
392     54-115
394     90-179
396    127-202
397      31-57
398     60-127
399     75-143
400    105-194
401      45-86
403     95-154
406     80-148
407      36-62
409     54-115
410      50-92
411     67-135
412     82-132
413     85-140
414    138-224
415      42-80
416     190-220
417     68-139
419      34-92
420      54-71
421     65-124
425      35-62
426    109-200
427      18-25
428     61-113
429      39-66
430      43-86
431     74-149
433    113-196
434     81-167
435     97-160
437      24-39
442      42-86
443     69-127
444    110-175
446    102-172
447     74-124
448      40-68
449    108-171
450     76-142
452    202-306
454      49-97
455     49-113
456      21-34
458     65-134
459      32-59
461     87-158
462    107-173
463      56-99
464      25-28
466     80-155
467      43-98
468      45-78
469      44-96
470     50-110
471     61-119
472     100-140
473      56-91
476     68-114
477     150-160
479    101-158
482    125-210
483      43-77
485    139-221
486      44-86
487     78-147
488     65-110
489      37-66
490      38-64
491      43-82
492      90-110
493     61-109
494     93-151
495      52-81
496     40-101
497     97-180
498     81-134
499     84-157
500     49-113
501     68-139
502     75-140
505    121-203
506      52-85
507     81-140
508      63-99
509     110-150
510     83-148
512     60-101
516      31-55
517    102-178
518     110-130
519      48-85
520     66-123
521     92-146
522      21-29
523      10-17
524    150-239
525      52-91
526      82-129
528     47-101
530      49-76
532      43-88
533    124-199
534      52-93
535     97-181
537    100-173
538      53-96
539      65-96
540      56-95
541    111-176
542     75-127
543     65-119
544      56-97
545    108-173
546     94-139
548    176-289
549     92-149
550     63-101
552     54-115
554    118-188
555    108-146
556     65-106
557      55-98
558     94-162
560     63-120
561     90-179
562    127-202
563     60-127
565      31-57
566    105-194
567      45-86
568     75-143
570    126-228
572     80-134
573    120-189
575     85-142
576     95-154
577    111-176
578     87-140
579     76-127
580      54-92
582     61-100
583     81-140
585     80-148
586    108-171
587    112-179
588     63-111
589     75-126
590    110-184
591     76-145
594      36-62
595     70-118
597     94-153
599     54-115
600      50-92
601      49-97
602     67-135
603    138-224
604     80-139
605    158-211
606    150-180
607      42-80
608     190-220
609      42-77
610     68-139
613      54-71
614      34-92
616      47-85
617     65-124
619      56-95
622     62-112
623    107-173
624     64-108
625     89-144
627    109-200
629     61-113
630      35-62
631     55-105
632      18-25
633      39-66
634    135-211
635      57-80
636    129-215
637     86-143
638     63-127
639      50-89
640      43-86
642     74-149
643     71-124
644    113-196
645     81-167
646     69-121
647     97-160
648    150-238
651     77-132
652      24-39
653     59-112
654      35-65
655     79-147
658     62-119
660    119-187
661     90-157
662      32-62
663      42-86
664    116-208
665    102-172
666     69-127
668     86-144
669    102-165
670     74-124
671      40-68
672     76-142
673     76-142
674    108-171
675    202-306
676     91-159
678     80-133
679      49-97
681     49-113
682      21-34
683     65-134
685      32-59
687      39-69
688     87-158
689      27-48
690      36-71
691    107-173
692      56-99
694      25-28
695     80-155
696      43-98
697      44-96
698      45-78
699     50-110
700      60-99
701    130-206
702     61-119
703     100-140
704     99-178
705     86-137
706     37-100
707     58-111
708     72-133
709      56-91
711     61-126
712     95-160
714      53-91
715    101-158
718      33-61
719      44-86
721      43-77
722    125-210
723      44-86
725     69-119
726     65-110
727     67-127
728     78-147
730     66-117
731      37-66
732     86-143
733     84-146
734      50-98
735      38-64
736      90-110
737     92-150
738     90-153
740      43-82
741     100-135
742     93-151
743     61-109
744      42-79
745    139-221
746     40-101
747     84-153
748      52-81
749     81-134
750     97-180
751     49-113
752      44-73
753     75-140
754     84-157
755      40-87
756     68-139
757     72-142
758     74-137
759     57-109
761    121-203
763      52-85
766     81-140
767     83-148
768     59-116
769     60-101
773      31-55
776    102-178
777    136-208
778     110-130
779      48-85
780     71-129
781     66-123
782    171-272
783     92-146
784     65-126
785    150-239
786      21-29
787      10-17
788    118-228
789      82-129
790      52-91
791     47-101
794      49-76
795      43-88
797     61-109
799    113-182
802    124-199
803     58-104
804      52-93
806     97-181
807    100-173
808     58-108
809     81-161
810      53-96
811     61-110
812      65-96
815    115-220
816     71-144
817      32-57
818     79-136
819     120-145
820      50-89
821     68-129
822     48-113
823      27-47
824     74-124
825     68-125
826      39-67
827     71-135
828    107-172
829      49-85
830      54-71
831     61-123
832      47-85
836     65-124
837     87-141
838      56-95
839     71-121
840     62-112
841     64-108
845     89-144
848    109-200
851      35-62
852     61-113
853     55-105
854      18-25
855    135-211
856      39-66
857      57-80
858     63-127
859      50-89
860     82-132
861     85-139
863     72-121
864     74-149
866    113-196
867     69-121
868     71-124
869     97-160
870     81-167
871    150-238
875      24-39
877      35-65
878     77-132
879      51-88
880    101-141
881     59-112
883     79-147
884     79-127
886     62-119
887    119-187
892     81-132
893     120-140
895     90-157
896     63-110
897      42-86
898      32-62
899    116-208
900    107-173
901     65-113
902     69-127
904    102-172
907     74-124
909      40-68
910     76-142
911     76-142
912    108-171
913    202-306
914     91-159
916     80-133
919      21-34
920      49-97
921     49-113
924     96-161
926     65-134
928     59-125
929      32-59
930     87-158
931      27-48
932      39-69
933      36-71
934    107-173
935      56-99
936      25-28
938     80-155
939      43-98
940      45-78
941     50-110
942      44-96
943     100-140
944     61-119
945     80-142
946     99-178
947     37-100
948     62-113
949     86-137
950     58-111
951     72-133
952      56-91
953     95-160
955     61-126
Name: Salary Estimate, dtype: str

In [ ]:
#Creating minimum and maximum salaries columns in the main df basis the prev column
df['min_salary'] = min_hr.apply(lambda x: int(x.split('-')[0]))
df['min_salary'].dtype
df['max_salary'] = min_hr.apply(lambda x: int(x.split('-')[1]))
df.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer_provided,min_salary,max_salary
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53,91
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63,112
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86,143

In [ ]:
df['avg_salary'] = (df.max_salary + df.min_salary)/2
df.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer_provided,min_salary,max_salary,avg_salary
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53,91,72.0
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63,112,87.5
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90,85.0
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86,143,114.5

## 4. Company Name Cleaning
- Remove rating text from company names

In [ ]:
#Standardizung company name to include texts only
#Numerical ratings are present at the end of company names(where rating > 0) which are 3 characters long.
#Removing the last 3 chars seems to be the easiest approach

df['company_txt'] = df.apply(lambda x: x['Company Name'] if x['Rating'] < 0 else x['Company Name'][:-3], axis = 1)
df.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Industry,Sector,Revenue,Competitors,hourly,employer_provided,min_salary,max_salary,avg_salary,company_txt
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,...,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53,91,72.0,Tecolote Research\n
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,...,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63,112,87.5,University of Maryland Medical System\n
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,...,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90,85.0,KnowBe4\n
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,...,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5,PNNL\n
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,...,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86,143,114.5,Affinity Solutions\n

## 5. Location Feature Engineering
- Extract state from location

In [ ]:
#State Field
df['job_state'] = df['Location'].apply(lambda x: x.split(',')[1])
df.head()
df.job_state.value_counts()

job_state
CA             151
MA             103
NY              72
VA              41
IL              40
MD              35
PA              33
TX              28
WA              21
NC              21
NJ              17
FL              16
OH              14
TN              13
CO              11
DC              11
IN              10
WI              10
UT              10
MO               9
AZ               9
AL               8
KY               6
MI               6
GA               6
DE               6
CT               5
IA               5
OR               4
LA               4
NE               4
NM               3
KS               3
MN               2
ID               2
Los Angeles      1
RI               1
SC               1
Name: count, dtype: int64

In [ ]:
#Creating an indicator for jobs in the same location as company headquarters
df.columns
df['same_state'] = df.apply(lambda x: 1 if x['Location'] == x['Headquarters'] else 0, axis = 1)
df.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Revenue,Competitors,hourly,employer_provided,min_salary,max_salary,avg_salary,company_txt,job_state,same_state
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,...,$50 to $100 million (USD),-1,0,0,53,91,72.0,Tecolote Research\n,NM,0
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,...,$2 to $5 billion (USD),-1,0,0,63,112,87.5,University of Maryland Medical System\n,MD,0
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,...,$100 to $500 million (USD),-1,0,0,80,90,85.0,KnowBe4\n,FL,1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,...,$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5,PNNL\n,WA,1
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,...,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86,143,114.5,Affinity Solutions\n,NY,1

## 6. Company Age Feature
- Calculate company age from founding year

In [ ]:
#age of company
df['age'] = df['Founded'].apply(lambda x: x if x < 0 else 2026 - x)
df.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Competitors,hourly,employer_provided,min_salary,max_salary,avg_salary,company_txt,job_state,same_state,age
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,...,-1,0,0,53,91,72.0,Tecolote Research\n,NM,0,53
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,...,-1,0,0,63,112,87.5,University of Maryland Medical System\n,MD,0,42
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,...,-1,0,0,80,90,85.0,KnowBe4\n,FL,1,16
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,...,"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5,PNNL\n,WA,1,61
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,...,"Commerce Signals, Cardlytics, Yodlee",0,0,86,143,114.5,Affinity Solutions\n,NY,1,28

## 7. Job Description Feature Engineering
- Calculate description length
- Extract skill keywords (Python, R, SQL, etc.)

In [ ]:
#Parsing of job description (Python etc)
df['Job Description']

df['python_yn'] = df['Job Description'].apply(lambda x: 1 if 'python' in x.lower() else 0)
df['python_yn'].value_counts()
df['R_yn'] = df['Job Description'].apply(lambda x: 1 if 'r studio' in x.lower() or 'r-studio' in x.lower() else 0)
df['sql'] = df['Job Description'].apply(lambda x: 1 if 'sql' in x.lower() else 0)
df['spark'] = df['Job Description'].apply(lambda x: 1 if 'spark' in x.lower() else 0)
df['aws'] = df['Job Description'].apply(lambda x: 1 if 'aws' in x.lower() else 0)
df['excel'] = df['Job Description'].apply(lambda x: 1 if 'excel' in x.lower() else 0)

In [ ]:
#dropping the first unnamed columm
df_out = df.drop(['Unnamed: 0'], axis = 1)

## 8. Final Dataset Export
- Save cleaned dataset for analysis

In [ ]:
#Exporting the final cleaned data
df_out.to_csv('salary_data_cleaned.csv', index = False)

In [ ]:
pd.read_csv('salary_data_cleaned.csv').head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,...,company_txt,job_state,same_state,age,python_yn,R_yn,spark,aws,excel,sql
0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,...,Tecolote Research\n,NM,0,53,1,0,0,0,1,0
1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,...,University of Maryland Medical System\n,MD,0,42,1,0,0,0,0,0
2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,...,KnowBe4\n,FL,1,16,1,0,1,0,1,1
3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,...,PNNL\n,WA,1,61,1,0,0,0,0,0
4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,...,Affinity Solutions\n,NY,1,28,1,0,0,0,1,1